/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;






/**
 *
 * @author enzol
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        NombreEmpresa1 = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        NombreEmpresa = new javax.swing.JLabel();
        IniciarSesion = new javax.swing.JLabel();
        UsuarioTxt = new javax.swing.JLabel();
        Usuarioimput = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ContrasenaTxt1 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        Entrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        registrarse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(36, 30, 26));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));

        NombreEmpresa1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        NombreEmpresa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreEmpresa1.setText("RestoManager");

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagen/logoSistemaNaranja.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreEmpresa1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(imagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(NombreEmpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 270, 500));

        NombreEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        NombreEmpresa.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        NombreEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        NombreEmpresa.setText("RestoManager");
        bg.add(NombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, 40));

        IniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSesion.setText("INICIAR SESIÓN");
        bg.add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        UsuarioTxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        UsuarioTxt.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioTxt.setText("USUARIO");
        bg.add(UsuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        Usuarioimput.setBackground(new java.awt.Color(36, 30, 26));
        Usuarioimput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Usuarioimput.setForeground(new java.awt.Color(153, 153, 153));
        Usuarioimput.setBorder(null);
        Usuarioimput.addActionListener(this::UsuarioimputActionPerformed);
        bg.add(Usuarioimput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 430, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 440, -1));

        ContrasenaTxt1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ContrasenaTxt1.setForeground(new java.awt.Color(255, 255, 255));
        ContrasenaTxt1.setText("CONTRASEÑA");
        bg.add(ContrasenaTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        Password.setBackground(new java.awt.Color(36, 30, 26));
        Password.setBorder(null);
        bg.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 430, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 343, 440, 10));

        Entrar.setBackground(new java.awt.Color(255, 153, 51));
        Entrar.setText("ENTRAR");
        Entrar.addActionListener(this::EntrarActionPerformed);
        bg.add(Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 180, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("No estas registrado? ");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 120, 20));

        registrarse.setForeground(new java.awt.Color(255, 153, 0));
        registrarse.setText("Registrate");
        registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarseMouseClicked(evt);
            }
        });
        bg.add(registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioimputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioimputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioimputActionPerformed

    
    
// TODO: Reemplazar con:
//   Usuario user = ServicioFactory.getAutenticacion().iniciarSesion(usuario, password);
//   if (user != null) { new Menu(user).setVisible(true); } else { mostrarError("Credenciales inválidas"); }
    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
            Menu menu = new Menu();
            menu.setVisible(true);
            
            this.dispose();
    }//GEN-LAST:event_EntrarActionPerformed

    private void registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMouseClicked
        Registro registro = new Registro();
        registro.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_registrarseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContrasenaTxt1;
    private javax.swing.JButton Entrar;
    private javax.swing.JLabel IniciarSesion;
    private javax.swing.JLabel NombreEmpresa;
    private javax.swing.JLabel NombreEmpresa1;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel UsuarioTxt;
    private javax.swing.JTextField Usuarioimput;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel registrarse;
    // End of variables declaration//GEN-END:variables
}
