/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.paneles;

import java.awt.Color;


/**
 *
 * @author enzol
 */
public class PedidosPanel extends javax.swing.JPanel {

    /**
     * Creates new form PedidosPanel
     */
    public PedidosPanel() {
        initComponents();
        
        configurarTabla();
    }
    
    
    private void configurarTabla() {

    javax.swing.table.DefaultTableCellRenderer headerRenderer =
            new javax.swing.table.DefaultTableCellRenderer();

    headerRenderer.setBackground(new Color(45, 30, 20));
    headerRenderer.setForeground(Color.WHITE);
    headerRenderer.setOpaque(true);

    for (int i = 0; i < TablaPedidos.getColumnModel().getColumnCount(); i++) {
        TablaPedidos.getColumnModel()
               .getColumn(i)
               .setHeaderRenderer(headerRenderer);
    }

   

    TablaPedidos.setForeground(Color.WHITE);
    TablaPedidos.setBackground(new Color(36, 30, 26));

    ScrollPedidos.setBackground(
            new Color(36, 30, 26));

    ScrollPedidos.getViewport().setBackground(
            new Color(36, 30, 26));
}

    
// TODO: Reemplazar con:
//   List<Producto> productos = ServicioFactory.getProductoServicio().obtenerTodos();
//   llenarTabla(productos);
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PedidosPanel = new javax.swing.JPanel();
        Encabezado2 = new javax.swing.JPanel();
        PedidosTitulo = new javax.swing.JLabel();
        FechaHora2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        FechaTxt = new javax.swing.JLabel();
        HoraTxt = new javax.swing.JLabel();
        HoraNum = new javax.swing.JLabel();
        FechaNum = new javax.swing.JLabel();
        PanelUsusario = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ScrollPedidos = new javax.swing.JScrollPane();
        TablaPedidos = new javax.swing.JTable();

        PedidosPanel.setBackground(new java.awt.Color(36, 30, 26));

        Encabezado2.setBackground(new java.awt.Color(36, 30, 26));
        Encabezado2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Encabezado2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PedidosTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PedidosTitulo.setForeground(new java.awt.Color(242, 242, 242));
        PedidosTitulo.setText("Pedidos");
        Encabezado2.add(PedidosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 129, 80));

        FechaHora2.setBackground(new java.awt.Color(36, 30, 26));

        jPanel10.setBackground(new java.awt.Color(109, 93, 83));
        jPanel10.setPreferredSize(new java.awt.Dimension(2, 50));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        FechaTxt.setForeground(new java.awt.Color(255, 255, 255));
        FechaTxt.setText("Fecha:");

        HoraTxt.setForeground(new java.awt.Color(255, 255, 255));
        HoraTxt.setText(" Hora:");

        HoraNum.setForeground(new java.awt.Color(255, 255, 255));
        HoraNum.setText("00:00");

        FechaNum.setForeground(new java.awt.Color(255, 255, 255));
        FechaNum.setText(" 00/00/0000");

        javax.swing.GroupLayout FechaHora2Layout = new javax.swing.GroupLayout(FechaHora2);
        FechaHora2.setLayout(FechaHora2Layout);
        FechaHora2Layout.setHorizontalGroup(
            FechaHora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FechaHora2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FechaHora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FechaHora2Layout.createSequentialGroup()
                        .addComponent(FechaTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FechaNum)
                        .addContainerGap())
                    .addGroup(FechaHora2Layout.createSequentialGroup()
                        .addComponent(HoraTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HoraNum))))
        );
        FechaHora2Layout.setVerticalGroup(
            FechaHora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FechaHora2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(FechaHora2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FechaHora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaTxt)
                    .addComponent(FechaNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FechaHora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoraTxt)
                    .addComponent(HoraNum))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Encabezado2.add(FechaHora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 150, 70));

        PanelUsusario.setBackground(new java.awt.Color(36, 30, 26));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Usuario");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Administrador");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagen/icon-icons (1).png"))); // NOI18N

        javax.swing.GroupLayout PanelUsusarioLayout = new javax.swing.GroupLayout(PanelUsusario);
        PanelUsusario.setLayout(PanelUsusarioLayout);
        PanelUsusarioLayout.setHorizontalGroup(
            PanelUsusarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUsusarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelUsusarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addContainerGap())
        );
        PanelUsusarioLayout.setVerticalGroup(
            PanelUsusarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsusarioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelUsusarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelUsusarioLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Encabezado2.add(PanelUsusario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 150, 70));

        ScrollPedidos.setBackground(new java.awt.Color(41, 34, 28));
        ScrollPedidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 93, 83)));

        TablaPedidos.setBackground(new java.awt.Color(41, 34, 28));
        TablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mesa", "Nombre", "Cant.", "Precio ", "Estado ", "Hora "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPedidos.setGridColor(new java.awt.Color(41, 34, 28));
        TablaPedidos.setSelectionBackground(new java.awt.Color(41, 34, 28));
        TablaPedidos.getTableHeader().setResizingAllowed(false);
        TablaPedidos.getTableHeader().setReorderingAllowed(false);
        TablaPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPedidosMouseClicked(evt);
            }
        });
        ScrollPedidos.setViewportView(TablaPedidos);

        javax.swing.GroupLayout PedidosPanelLayout = new javax.swing.GroupLayout(PedidosPanel);
        PedidosPanel.setLayout(PedidosPanelLayout);
        PedidosPanelLayout.setHorizontalGroup(
            PedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado2, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
            .addGroup(PedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PedidosPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ScrollPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        PedidosPanelLayout.setVerticalGroup(
            PedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidosPanelLayout.createSequentialGroup()
                .addComponent(Encabezado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 620, Short.MAX_VALUE))
            .addGroup(PedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidosPanelLayout.createSequentialGroup()
                    .addContainerGap(83, Short.MAX_VALUE)
                    .addComponent(ScrollPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PedidosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PedidosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TablaPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPedidosMouseClicked
        
    }//GEN-LAST:event_TablaPedidosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Encabezado2;
    private javax.swing.JPanel FechaHora2;
    private javax.swing.JLabel FechaNum;
    private javax.swing.JLabel FechaTxt;
    private javax.swing.JLabel HoraNum;
    private javax.swing.JLabel HoraTxt;
    private javax.swing.JPanel PanelUsusario;
    private javax.swing.JPanel PedidosPanel;
    private javax.swing.JLabel PedidosTitulo;
    private javax.swing.JScrollPane ScrollPedidos;
    private javax.swing.JTable TablaPedidos;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel10;
    // End of variables declaration//GEN-END:variables
}
