# Database connection details (TiDB Cloud Serverless)
db.url=jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/restaurante_db?useSSL=true&sslMode=VERIFY_IDENTITY
db.user=2nzk3nduoAYa8LR.root
db.password=zl1hFlifUL7vbi2u
