# Database connection details (TiDB Cloud Serverless)
db.url=jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/test?useSSL=true&sslMode=VERIFY_IDENTITY
db.user=3UVXjhF7mJPRv7j.root
db.password=DDFGrxHjuJ9VHIzQ

